version: 1.0.{build}
image: Visual Studio 2017
install:
- ps: >-
    choco install go-ipfs

    choco install pester

    ipfs init

    Start-Process -FilePath "ipfs.exe" -ArgumentList "daemon"
before_build:
- ps: nuget restore
build:
  verbosity: minimal
test_script:
- ps: >-
    ipfs files mkdir -p /test/does/not/exist/yet


    vstest.console /logger:Appveyor bin/IpfsTests.dll


    $res = Invoke-Pester -Path ".\IpfsProviderPowerShellTests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru


    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))


    if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}